### ISSUE TITLE
Sub-Menu

### ISSUE THREAD

**Issue by afngncgg** [paulosalvatore/Ocean_Android_Listas_Multithread_25_06_2021#1]
Oi Paulo,
Para contruir outra Lista, repetimos o processo dentro de outra lista, uma segunda tela e ela entao sera um sub-menu?.

**Comment by paulosalvatore** [comment]
Se você colocar cada `item` da primeira `RecyclerView` para abrir uma nova tela no `onClick`, essa nova tela pode ter outra `RecyclerView`, mas essa nova `RecyclerView` não será um submenu.

Se você quiser construir uma segunda `RecyclerView` dentro de cada `item` da primeira `RecyclerView`, a apenas alterar a visibilidade dela, fica mais parecido com o sistema de submenu.

Entretanto, dependendo do que vc quer criar, podemos pensar em formas alternativas de exibir esse conteúdo, algo que fique melhor em termos de navegação.
